#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "/Users/satyakhanda/Desktop/University/Year 4/CPSC/427/A1_A3_student_template/cpsc-427-dev/template/"
